DROP TABLE ZIPCODE CASCADE;

CREATE TABLE ZIPCODE (
	id INTEGER NOT NULL AUTO_INCREMENT,
	zipcode VARCHAR(10) NOT NULL,
	county VARCHAR(30) NOT NULL,
	areacode VARCHAR(10) NOT NULL,
	PRIMARY KEY (id)
);

